name: electricity_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  carousel_slider: ^5.0.0
  easy_stepper: ^0.8.5+1
  webview_flutter: ^4.11.0
  shared_preferences: ^2.5.3
  panara_dialogs: ^0.1.5
  firebase_core: ^3.13.0
  firebase_remote_config: ^5.4.3
  google_mobile_ads: ^6.0.0
  shimmer: ^3.0.0
  connectivity_plus: ^6.1.4
  url_launcher: ^6.3.1
  geolocator: ^14.0.0
  weather: ^3.2.1
  onesignal_flutter: ^5.3.0
  # enhance_stepper: ^1.0.2
  # tuple: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.7.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/appIcon.png"
  background_color: "transparent"
  adaptive_icon_background: "transparent"

flutter_gen:
  output: lib/gen/

flutter:
  uses-material-design: true

  assets:
    - assets/

#scripts:
#  gen: flutter pub run build_runner build --delete-conflicting-outputs
